<?php
/**
 * Plugin Name:       SafeSchema
 * Plugin URI:        https://hostcodelab.com/
 * Description:       Add validated custom JSON-LD to individual posts, pages, and public custom post types. Optionally replace schema generated by supported SEO plugins on that URL.
 * Version:           1.0.0-beta.1
 * Author:            Hostcode Lab
 * Author URI:        https://hostcodelab.com/
 * Text Domain:       safeschema
 * Requires at least: 6.2
 * Requires PHP:      7.4
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'SAFESCHEMA_VERSION', '1.0.0-beta.1' );
define( 'SAFESCHEMA_FILE', __FILE__ );
define( 'SAFESCHEMA_DIR', plugin_dir_path( __FILE__ ) );
define( 'SAFESCHEMA_URL', plugin_dir_url( __FILE__ ) );

require_once SAFESCHEMA_DIR . 'includes/class-safeschema-validator.php';
require_once SAFESCHEMA_DIR . 'includes/class-safeschema-plugin.php';

SafeSchema\Plugin::instance();
